### ISSUE TITLE
check for python versions

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#21]
check if brdr works for python v3.7->...->v3.12

**Comment by koenedaele** [comment]
Currently we're supporting >= 3.9? 

There's a security vulnerability for requests that requires an update that no longer works on python 3.7. So looks like supporting 3.7 will become difficult.

**Comment by koenedaele** [comment]
Do we need a specific version for QGIS?

**Comment by dieuska** [comment]
QGIS works with python 3.9.  
So at least 3.9 has to be supported.  
This is ok for the brdr 0.1.0-release. (I only had to make one fix for Enums  (StrEnum) that was not supported by 3.9, but is OK in the current code

**Comment by dieuska** [comment]
CI added for python 3.9 ->3.12: see https://github.com/OnroerendErfgoed/brdr/issues/25
