### ISSUE TITLE
dependency on matplotlib, pandas & geopandas not necessary for brdr-package?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#22]
It seems the brdr-package does not use matplotlib as a main dependency? Can it be removed from the pyproject.toml?

At this moment 'matplotlib' is used to show results and plot graphics, but these functions are only used in the examples.
Or are we going to add these visualisation/report-functions to de brdr-package?

**Comment by dieuska** [comment]
The same for pandas & geopandas, I will change title

**Comment by koenedaele** [comment]
Sounds like a dev dependency, not a runtime dependency.
