### ISSUE TITLE
CRS handling

### ISSUE THREAD

**Issue by maarten-vermeyen** [OnroerendErfgoed/brdr#3]
The class AutoReferencer seems to only use the CRS in a very limited number of cases (GRB methods to load data directly from GRB, export, ...). At the moment, these methods seem to make the class less usable for generic (non-Belgian) reference layers, as there are no methods of setting the CRS (apart from overwriting the class constant). 

This raises several questions:

- should CRS be a class constant or be an instance attribute?
- should the methods that are GRB specific be in a inherited class (GRBAutoReference), as users outside of Flanders will not need them (and it now seems to limit use outside of Belgium, as only Belgian CRS's can be exported)?
- is a class constant the best way to set the default CRS?

**Comment by dieuska** [comment]
CRS as init-parameter (instance) of Aligner-class: https://github.com/OnroerendErfgoed/brdr/commit/8e5fdc346162b4387561e689b1156c0324c39817

**Comment by dieuska** [comment]
fyi: closed this ticket as crs is now a instance-attribute. the question to refactor all the 'not-generic' functionalities is added to a new ticket: https://github.com/OnroerendErfgoed/brdr/issues/17
