### ISSUE TITLE
Difference operation returns geometries with zero area

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/brdr#45]
The difference operations for already aligned input geometries, seem to result in geometries with no area:
https://github.com/OnroerendErfgoed/brdr/blob/19d173a9665a6e0a2cc8c2a97a1fd3e6354b994c/brdr/aligner.py#L884-L885
![image](https://github.com/user-attachments/assets/4846660e-2eb2-4b1b-bdbc-ef3023d263f2)

**Comment by dieuska** [comment]
@roefem , does this issue still apply, or can we close this issue?

**Comment by maarten-vermeyen** [comment]
Closing this issue a s this results in an valid empty geometry and is de default behaviour  for difference operations in most GIS libraries.
