### ISSUE TITLE
thematic input multipolygon consisting of overlapping geometries results in overlapping part being excluded from result

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/brdr#46]
![image](https://github.com/user-attachments/assets/453b128f-7ced-45cb-bc23-2944faa3d2a3)

**Comment by dieuska** [comment]
@roefem : Do you have an ID of the feature that I can use for reproducing this case?

**Comment by dieuska** [comment]
@roefem :
n the example ' example_multi_to_single.py ', we use a function to make single polygons from all Multipolygon existing out of multiple parts. So the algorithm handles them seperately. At the end, these results are combined.

In brdrQ we have a checkbox to let the user choose to handle 'multis_as_single' or not. 

If it would be a solution , we can  add a parameter 'multi_as_single=True/False' to the algorithm.  At the moment we have chosen to keep this out of the algorithm, and we added  helper-functions (multipolygons_to_singles, merge_process_results) for the user to manipulate the input and the result.

**Comment by dieuska** [comment]
This case is fixed in 'development'-branch, by executing a unary_union on the input-multipolygon, so overlapping area in in the input-geometry are disolved
