### ISSUE TITLE
Add a CITATION.cff file

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/brdr#5]
Needed to archive to Zenodo

Reference the report as well (although the report is in Dutch)

**Comment by maarten-vermeyen** [comment]
Gemerged in main, voorlopig zonder identifier.

**Comment by dieuska** [comment]
@maarten-vermeyen : moet hiervoor nog iets gebeuren, of kan deze afgesloten worden?

**Comment by koenedaele** [comment]
Mag gesloten worden. Als er nog wijzigingen nodig zijn, maken we wel specifieke tickets aan.
