### ISSUE TITLE
Input geometry area limit

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/brdr#50]
The aligner should have an option to limit the size of the input geometry, to prevent resource heavy processing.

**Comment by dieuska** [comment]
@roefem Should this area be limited in the python-library, or is this only a concern for the webservice?

The python library can handle big geometries. It mostly depends on the combination of which referencelayer is used. 
When using parcels, a lot of parcels are covered with a geometry of 100000m², but if you take for example municipality-borders as referencelayer it's maybe not a problem to have inputgeometries of 100000m².

**Comment by dieuska** [comment]
@roefem ; When a dictionary of multiple geometries is processed, will only the big geometry be blocked, and all the other geometries will be processed?; or will the full dictionary be blocked?

**Comment by roefem** [comment]
I think it's the responsibility of the library to allow for a way to limit the area size, but the webservice should determine what this limit is.
Only the geometries that are too big will be skipped, the others will still be processed as normal

**Comment by maarten-vermeyen** [comment]
This issue seems resolved. Can it be closed?

**Comment by dieuska** [comment]
for me , it can be closed, 
@roefem, ok?
