### ISSUE TITLE
refactor the structure of the (internal) dicts: dict_series, dict_predicted,....

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#57]
In the current code, when executing a series of calculation for multiple relevant distances, the result is arranged by relevant distance: (key = relevant distance).
It should be better to always give results arranged on thematic_id (key=thematic_id) because most of the functionalities is based on the fact that we want to do calculations, predictions etc. for all thematic objects.

At the moment this structure has to be re-arranged multiple times (util-function: dict_series_by_keys). If we would do this refactoring, this re-arrangement shouldn't be necessary anymore resulting in less handling.

So I would propose to always give results in following order:
![image](https://github.com/user-attachments/assets/903a582e-9667-4b49-b5cd-438c778d0a7d)

This could be a big refactoring as this is used in multiple functions

**Comment by dieuska** [comment]
@roefem what do you think about this remark?

**Comment by roefem** [comment]
Seems good to me, I don't see any issues with reordering the way dict_series is composed

**Comment by dieuska** [comment]
when executing; to test if this refactoring is really faster? (at least it looks more logic to me to do this refactoring

**Comment by dieuska** [comment]
Added 'example_speedtest.py'; an example to measure the speed of execution (10 times) before and after refactoring:

Results:

# #BEFORE REFACTORING dict_series
# duration: [25.652311, 27.894154, 19.641618, 19.929254, 44.754033, 25.218422, 23.167992, 18.649832, 22.899336, 52.108296]
# Min: 18.649832
# Max: 52.108296
# Mean: 27.9915248
# Median: 24.193207
# Stdv: 11.28891821173264

# #AFTER refactoring
# duration: [21.313991, 16.558168, 16.590126, 18.111118, 16.872433, 17.928071, 18.32295, 17.87116, 19.516652, 16.729241]
# Min: 16.558168
# Max: 21.313991
# Mean: 17.981391
# Median: 17.8996155
# Stdv: 1.504459449440969

Conclusion: refactoring resulted in faster execution-times
