### ISSUE TITLE
refactoring of 'formula-unction': generic vs GRB

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdr#59]
At the moment we have a aligner.get_formula()-function that transforms a geometry in a json-discription of the geometry based on all the reference-geometries. This can be used generic.

Example of the current formula-structure:
![image](https://github.com/user-attachments/assets/16a8c9b6-8681-427e-9495-183d41b58c70)

As we notice, when using this formula for GRB-purposes we need to enrich this formula with GRB-specific attributes (f.e. version_date)

So at the moment the formula-function-code becomes a mix between generic and GRB-specific elements
What would be the best structure to seperate the generic from the GRB-specific so it is more future-proof?

**Comment by dieuska** [comment]
@roefem : what is your idea about this?

**Comment by roefem** [comment]
Je zou in de Loader classes een extend_formula functie kunnen steken, die de formula met loader-specifieke velden aanvult
